doctrine_migrations:
    # List of namespace/path pairs to search for migrations, at least one required
    migrations_paths:
        'App\Migrations': 'src/App'

    # Connection to use for the migrations
    connection: default