options:
  docker: true

pipelines:
  default:
    - step:
        image: google/cloud-sdk:latest
        caches:
          - docker
        services:
          - docker
        script:
          - export IMAGE_NAME=$HOSTNAME/$PROJECTID/$IMAGE # ex. gcr.io/my-g-project/my-cr-service
          - export SERVICE_NAME=$CLOUDRUN_SERVICE_NAME

          - docker build -t $IMAGE_NAME .
          - docker tag rauchfussio $IMAGE_NAME

          - gcloud auth activate-service-account $SERVICE_ACCOUNT --key-file=credentials/rauchfuss-io-5ba2172ea3b0.json
          - gcloud config list
          - gcloud auth configure-docker -q

          - docker push rauchfussio

          - gcloud beta run deploy $SERVICE_NAME --image $IMAGE_NAME --platform managed --region europe-west1
