options:
  docker: true

pipelines:
  default:
    - step:
        name: Build
        image: atlassian/default-image:2
        caches:
          - docker
        services:
          - docker
        script:
          - export IMAGE_NAME=$HOSTNAME/$PROJECTID/$IMAGE # ex. gcr.io/my-g-project/my-cr-service
          - docker build -t rauchfussio .
          - docker tag rauchfussio $IMAGE_NAME
    - step:
        name: Auth
        image: google/cloud-sdk:latest
        script:
          - gcloud auth activate-service-account $SERVICE_ACCOUNT --key-file=credentials/rauchfuss-io-5ba2172ea3b0.json
          - gcloud config list
          - gcloud auth configure-docker -q
    - step:
        name: Push
        script:
          - export IMAGE_NAME=$HOSTNAME/$PROJECTID/$IMAGE # ex. gcr.io/my-g-project/my-cr-service
          - docker push $IMAGE_NAME
    - step:
        name: Deploy
        image: google/cloud-sdk:latest
        script:
          - gcloud beta run deploy $CLOUDRUN_SERVICE_NAME --image $IMAGE_NAME --platform managed --region europe-west1 --project $GCP_PROJECTID
