options:
  docker: true

pipelines:
  branches:
      master:
        - step:
            name: install dependencies
            image: composer
            caches:
              - composer
            artifacts:
              - vendor/**
            script:
              - composer install --ignore-platform-reqs
        - step:
            name: build & push to GCP registry
            image: google/cloud-sdk:latest
            script:
              - export IMAGE_NAME=$HOSTNAME/$PROJECTID/$IMAGE

              - sed -i "/BUILD=/c\BUILD=$BITBUCKET_COMMIT" .env

              - echo $CLIENT_CREDENTIALS > rauchfuss-io-5ba2172ea3b0.json | gcloud auth activate-service-account $SERVICE_ACCOUNT --key-file=./rauchfuss-io-5ba2172ea3b0.json
              - gcloud config list
              - gcloud auth configure-docker -q
              - docker build -t rauchfussio .
              - docker tag rauchfussio $IMAGE_NAME
              - docker push $IMAGE_NAME
        - step:
            name: deploy to CloudRun staging
            image: google/cloud-sdk:latest
            script:
              - export IMAGE_NAME=$HOSTNAME/$PROJECTID/$IMAGE

              - echo $CLIENT_CREDENTIALS > rauchfuss-io-5ba2172ea3b0.json | gcloud auth activate-service-account $SERVICE_ACCOUNT --key-file=./rauchfuss-io-5ba2172ea3b0.json
              - gcloud config list
              - gcloud auth configure-docker -q
              - gcloud beta run deploy $CLOUDRUN_STAGING_SERVICE_NAME --image $IMAGE_NAME --platform managed --region europe-west1 --project $GCP_PROJECTID
        - step:
            name: deploy to CloudRun production
            image: google/cloud-sdk:latest
            trigger: manual
            script:
              - export IMAGE_NAME=$HOSTNAME/$PROJECTID/$IMAGE

              - echo $CLIENT_CREDENTIALS > rauchfuss-io-5ba2172ea3b0.json | gcloud auth activate-service-account $SERVICE_ACCOUNT --key-file=./rauchfuss-io-5ba2172ea3b0.json
              - gcloud config list
              - gcloud auth configure-docker -q
              - gcloud beta run deploy $CLOUDRUN_PROD_SERVICE_NAME --image $IMAGE_NAME --platform managed --region europe-west1 --project $GCP_PROJECTID
