version: 2.1

references:
  image_name: &image_name
    eu.gcr.io/rauchfuss-io/rauchfuss-io

  auth: &auth
    run:
      name: Auth against GCP
      command: |
        echo $CLIENT_CREDENTIALS | gcloud auth activate-service-account --key-file=-
        gcloud config list
        gcloud auth configure-docker -q

  copy_vendor: &copy_vendor
    run:
      name: Copy vendor directory
      command: cp -R /tmp/vendor .

jobs:
  install_dependencies:
    docker:
      - image: composer:1.9
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'composer-{{ checksum "composer.lock"  }}'
      - run: composer install --ignore-platform-reqs
      - save_cache:
          key: 'composer-{{ checksum "composer.lock"  }}'
          paths:
            - vendor
      - persist_to_workspace:
          root: .
          paths:
            - vendor

  test_functional:
    docker:
      - image: circleci/php:cli
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - *copy_vendor
      - run: ./bin/phpunit

  test_lint:
    docker:
      - image: circleci/php:cli
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - *copy_vendor
      - run: ./vendor/bin/phplint

  build_and_deploy_image:
    environment:
      - IMAGE_NAME: *image_name
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - checkout
      - *auth
      - setup_remote_docker
      - attach_workspace:
          at: /tmp
      - *copy_vendor
      - run:
          name: Update Build-Hash
          command: sed -i "/BUILD=/c\BUILD=$CIRCLE_SHA1" .env
      - restore_cache:
          keys:
            - 'docker-{{ checksum "/caches/rauchfussio.tar"  }}'
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/rauchfussio.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=rauchfussio -t rauchfussio .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/rauchfussio.tar rauchfussio
      - save_cache:
          key: 'docker-{{ checksum "/caches/rauchfussio.tar"  }}'
          paths:
            - /caches/rauchfussio.tar
      - run:
          name: Build Image & Push to Container Registry
          command: |
            docker tag rauchfussio $IMAGE_NAME
            docker push $IMAGE_NAME

  deploy_revision_staging:
    environment:
      - IMAGE_NAME: *image_name
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - *auth
      - run:
          name: Deploy new Revision
          command: gcloud beta run deploy $CLOUDRUN_STAGING_SERVICE_NAME --image $IMAGE_NAME --platform managed --region europe-west1 --project $GCP_PROJECTID

  deploy_revision_production:
    environment:
      - IMAGE_NAME: *image_name
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - *auth
      - run:
          name: Deploy new Revision
          command: gcloud beta run deploy $CLOUDRUN_PROD_SERVICE_NAME --image $IMAGE_NAME --platform managed --region europe-west1 --project $GCP_PROJECTID

workflows:
  version: 2
  "Build, Test and Deploy":
    jobs:
      - install_dependencies
      - test_functional:
          requires:
            - install_dependencies
      - test_lint:
          requires:
            - install_dependencies
      - build_and_deploy_image:
          requires:
            - install_dependencies
            - test_functional
            - test_lint
      - deploy_revision_staging:
          requires:
            - build_and_deploy_image
      - hold:
          type: approval
          requires:
            - install_dependencies
            - test_functional
            - test_lint
            - deploy_revision_staging
      - deploy_revision_production:
          requires:
            - hold