version: 2.1

references:
  image_name: &image_name
    eu.gcr.io/rauchfuss-io/rauchfuss-io

  auth: &auth
    run:
      name: Auth against GCP
      command: |
        echo $CLIENT_CREDENTIALS | gcloud auth activate-service-account --key-file=-
        gcloud config list
        gcloud auth configure-docker -q

jobs:
  install_dependencies:
    docker:
      - image: composer:1.9
    steps:
      - checkout
      - run: composer install --ignore-platform-reqs
      - persist_to_workspace:
          root: .
          paths:
            - vendor

  build_and_deploy_image:
    environment:
      - IMAGE_NAME: *image_name
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - checkout
      - *auth
      - setup_remote_docker
      - attach_workspace:
          at: /tmp
      - run:
          name: Copy vendor directory
          command: cp -R /tmp/vendor .
      - run:
          name: Update Build-Hash
          command: sed -i "/BUILD=/c\BUILD=$CIRCLE_SHA1" .env
      - run:
          name: Build Image & Push to Container Registry
          command: |
            docker build -t rauchfussio .
            docker tag rauchfussio $IMAGE_NAME
            docker push $IMAGE_NAME

  deploy_revision_staging:
    environment:
      - IMAGE_NAME: *image_name
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - *auth
      - run:
          name: Deploy new Revision
          command: gcloud beta run deploy $CLOUDRUN_STAGING_SERVICE_NAME --image $IMAGE_NAME --platform managed --region europe-west1 --project $GCP_PROJECTID

  deploy_revision_production:
    environment:
      - IMAGE_NAME: *image_name
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - *auth
      - run:
          name: Deploy new Revision
          command: gcloud beta run deploy $CLOUDRUN_PROD_SERVICE_NAME --image $IMAGE_NAME --platform managed --region europe-west1 --project $GCP_PROJECTID

workflows:
  version: 2
  "Build, Test and Deploy":
    jobs:
      - install_dependencies
      - build_and_deploy_image:
          requires:
            - install_dependencies
      - deploy_revision_staging:
          requires:
            - build_and_deploy_image
      - hold:
          type: approval
          requires:
            - install_dependencies
            - deploy_revision_staging
      - deploy_revision_production:
          requires:
            - hold