version: 2.1
jobs:
  build:
    docker:
      - image: composer:1.9
    steps:
      - checkout
      - run: composer install --ignore-platform-reqs
      - persist_to_workspace:
          root: .
          paths:
            - vendor

  deploy:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
          name: Auth against GCP
          command: |
            echo $CLIENT_CREDENTIALS | gcloud auth activate-service-account --key-file=-
            gcloud config list
            gcloud auth configure-docker -q
      - setup_remote_docker
      - run:
          name: Build Image & Push to Container Registry
          command: |
            docker build -t rauchfussio .
            docker tag rauchfussio $HOSTNAME/$PROJECTID/$IMAGE
            docker push $HOSTNAME/$PROJECTID/$IMAGE

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master