version: 2.1
jobs:
  build:
    docker:
      - image: composer:1.9
    steps:
      - checkout
      - run: composer install --ignore-platform-reqs

  deploy:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: export IMAGE_NAME=$HOSTNAME/$PROJECTID/$IMAGE
      - run:
          name: Auth against GCP
          command: |
            echo $CLIENT_CREDENTIALS > rauchfuss-io-5ba2172ea3b0.json | gcloud auth activate-service-account $SERVICE_ACCOUNT --key-file=./rauchfuss-io-5ba2172ea3b0.json
            gcloud config list
            gcloud auth configure-docker -q
      - run:
          name: Build Image & Push to Container Registry
          command: |
            docker build -t rauchfussio .
            docker tag rauchfussio $IMAGE_NAME
            docker push $IMAGE_NAME

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master