version: 2.1
jobs:
  build:
    docker:
      - image: composer:1.9
    steps:
      - checkout
      - run: composer install --ignore-platform-reqs
    store_artifacts:
      path: /vendor

workflows:
  version: 2
  build:
    jobs:
      - build