version: 2.1

references:
  auth: &auth
    run:
      name: Auth against GCP
      command: |
        echo $CLIENT_CREDENTIALS | gcloud auth activate-service-account --key-file=-
        gcloud config list
        gcloud auth configure-docker -q


jobs:
  build:
    docker:
      - image: composer:1.9
    steps:
      - checkout
      - run: composer install --ignore-platform-reqs
      - persist_to_workspace:
          root: .
          paths:
            - vendor

  deploy_image:
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - checkout
      - *auth
      - setup_remote_docker
      - attach_workspace:
          at: /tmp
      - run:
          name: Copy vendor directory
          command: cp -R /tmp/vendor .
      - run:
          name: Build Image & Push to Container Registry
          command: |
            docker build -t rauchfussio .
            docker tag rauchfussio $HOSTNAME/$PROJECTID/$IMAGE
            docker push $HOSTNAME/$PROJECTID/$IMAGE

  deploy_revision:
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - *auth
      - gcloud beta run deploy $CLOUDRUN_STAGING_SERVICE_NAME --image $IMAGE_NAME --platform managed --region europe-west1 --project $GCP_PROJECTID

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy_image:
          requires:
            - build
      - deploy_revision:
          requires:
            - deploy_image